project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "© 2025 Christopher Jacobs | Researcher at Clemson University"
  navbar:
    search: false
    title: Christopher Jacobs
    right:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      # - href: blog/index.qmd
      #   text: Blog
      # - href: art/index.qmd
      #   text: Art/Media

resources:
  - "files/"
  - "*.pdf"
  - "JacobsChristopher_Resume.pdf"
  - "projects/images/**"
  - "research/images/**"
    
format:
  html:
    mainfont: "monospace"
    fontsize: 20p
    theme: [cosmo, styles.scss]
    # include-after-body: footer_nav.html

