project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Footer"
  navbar:
    search: false
    title: Christopher Jacobs
    right:
      - href: projects/index.qmd
        text: Projects
      - href: research/index.qmd
        text: Research
      - href: blog/index.qmd
        text: Blog
      - href: art/index.qmd
        text: Art/Media

resources:
  - "files/"
  - "*.pdf"
  - "JacobsChristopher_Resume.pdf"
    
format:
  html:
    mainfont: "monospace"
    fontsize: 20p
    theme: [cosmo, styles.scss]

